owner: madhogs
repo: upptime

sites:
  - name: Website
    url: https://$DOMAIN_WEBSITE
  - name: Website Subdomain
    url: https://www.$DOMAIN_WEBSITE

status-website:
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Changes:
# Remove schedule from update-template.yml
# Remove update-template step from setup.yml
#
# Add below after checkout step to uptime.yml, setup.yml and response-time.yml
# - name: Tailscale
#   uses: tailscale/github-action@v2
#   with:
#     version: '1.50.1'
#     oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
#     oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
#     tags: tag:ci
