owner: madhogs
repo: upptime

sites:
  - name: qBittorrent public
    check: "tcp-ping"
    url: $SITE_URL_QBITTORRENT_PUBLIC
    port: $SITE_PORT_QBITTORRENT_PUBLIC
  - name: Monero public
    check: "tcp-ping"
    url: $BASE_URL_MADHOGS
    port: $SITE_PORT_MONERO_PUBLIC
  - name: Tor bridge OR public
    check: "tcp-ping"
    url: $BASE_URL_MADHOGS
    port: $SITE_PORT_TOR_OR_PUBLIC
  - name: Tor bridge PT public
    check: "tcp-ping"
    url: $BASE_URL_MADHOGS
    port: $SITE_PORT_TOR_PT_PUBLIC
  - name: Vpn Proxy
    check: "tcp-ping"
    url: $VPS_URL
    port: $SITE_PORT_VPN_PROXY
  - name: Tor Proxy
    check: "tcp-ping"
    url: $VPS_URL
    port: $SITE_PORT_TOR_PROXY
  - name: Portainer Agent
    check: "tcp-ping"
    url: $VPS_URL
    port: $SITE_PORT_PORTAINER_AGENT
  - name: qBitTorrent UI
    url: $SITE_URL_QBITTORRENT_UI
  - name: Jellyfin UI
    url: $SITE_URL_JELLYFIN_UI
  - name: Portainer UI
    url: $SITE_URL_PORTAINER_UI
  

status-website:
  cname: status.madhogs.dev
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Changes:
# Remove schedule from update-template.yml
#
# Add below step before Check endpoint status to uptime.yml
# - name: Tailscale
#   uses: tailscale/github-action@v1
#   with:
#     authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
