owner: madhogs
repo: upptime

sites:
  - name: qBittorrent public
    check: "tcp-ping"
    url: $SITE_URL_QBITTORRENT_PUBLIC
    port: $SITE_PORT_QBITTORRENT_PUBLIC
  - name: Monero public
    check: "tcp-ping"
    url: $BASE_URL_MADHOGS
    port: $SITE_PORT_MONERO_PUBLIC
  - name: Tor bridge OR public
    check: "tcp-ping"
    url: $BASE_URL_MADHOGS
    port: $SITE_PORT_TOR_OR_PUBLIC
  - name: Tor bridge PT public
    check: "tcp-ping"
    url: $BASE_URL_MADHOGS
    port: $SITE_PORT_TOR_PT_PUBLIC

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
