name: Notify
on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:
jobs:
  notify:
    name: Send notification
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          version: '1.50.1'
      - name: Send notification
        run: |
          HEADER="Content-Type: application/json"
          URL="http://pi:${{ secrets.SITE_PORT_SIGNAL }}/v2/send"
          MESSAGE="Test message"
          BODY="{\"message\": \"$MESSAGE\", \"number\": \"${{ secrets.NOTIFY_NUMBER }}\", \"recipients\": [ \"${{ secrets.NOTIFY_NUMBER }}\" ]}"
          curl -X POST -H "$HEADER" "$URL" -d "$BODY"
